---
sudo: false
cache:
  directories:
    - $HOME/.cpanm
    - $HOME/perl5/perlbrew/perls/5.16/lib/site_perl
    - /var/tmp
addons:
  apt:
    packages:
    - build-essential
    - libgd2-xpm-dev
    - libssl-dev
    - git
    - libxml2-dev
    - libpango1.0-dev
    - imagemagick
before_install:
  - export HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
  - git config --global user.name "Dist Zilla Plugin TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
  - cpanm  --quiet  --notest --skip-installed Dist::Zilla
  - dzil authordeps | grep -ve '^\W' | xargs -n 5 -P 10 cpanm  --quiet   --notest  --skip-installed --mirror http://www.cpan.org/ --mirror http://duckpan.org/
  - dzil listdeps | grep -ve '^\W' | cpanm  --quiet   --notest  --skip-installed --mirror http://www.cpan.org/ --mirror http://duckpan.org/
  - npm install grunt-cli
  - npm install
  - bower install
  - export PATH=$PERLBREW_PATH:$PATH
language: perl
perl:
  - 5.16
node_js:
  - 4.2
script:
  - dzil smoke --release --author
  - grunt test-ia
